baseURL = "https://brettimkopf.github.io/Kacken-auf-Wacken"
languageCode = 'de_de'
title = 'Kacken auf Wacken'
theme = "hello-friend-ng"
defaultContentLanguage = "en"
EnableThemeToggle = "false"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[languages]
  [languages.en]
    languageName = "English"
    weight = 1

  [languages.de]
    languageName = "Deutsch"
    weight = 2

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"
	EnableThemeToggle = "true"
	
  # Subtitle for home
  homeSubtitle = "Die Spielregeln"

[params.footer]	
trademark = "BrettImKopf"

[params.logo]
	path = "images/logo.png"
    alt = "Kacken auf Wacken"
	
[params.author]
	name = "Stephan Noll"
 

[[menu.main]]
  identifier = "main"
  name = "Spielregeln"
  link = "#main"
  url = "/"
  weight = 1
  [menu.main.params]
  caption = "Zurück zu den Spielregeln"
