baseURL = "https://brettimkopf.github.io/Kacken-auf-Wacken"
languageCode = "de-de"
title = "Kacken auf Wacken"
theme = "zen"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[params]
favicon = "favicon.png"
icon = "favicon.png"
sitename = false
copyright = "© [BrettImKopf](https://github.com/BrettImKopf/Kacken-auf-Wacken)"
poweredby = true
menuInHeader = false        # Move the main menu to the header, default false.
mobileMenuOutline = true   # Mobil menu button as outline, default false.
[[menu.main]]
  identifier = "main"
  name = "Startseite"
  link = "#main"
  url = "/"
  weight = 5
  [menu.main.params]
  caption = "Zurück zur Hauptseite"
[[menu.main]]
  identifier = "zubehoer"
  name = "Zubehör"
  link = "#zubehoer"
  url = "/zubehoer"
  weight = 3
  [menu.main.params]
  caption = "Zubehör"
[[menu.main]]
  identifier = "quickstart"
  name = "Quickstart"
  link = "#quickstart"
  url = "/quickstart"
  weight = 4
  [menu.main.params]
  caption = "Schnellstart"
[[menu.main]]
  identifier = "introduction"
  name = "Einführung"
  link = "#introduction"
  url = "/introduction"
  weight = 1
  [menu.main.params]
  caption = "Einführung"
[[menu.main]]
  identifier = "tutorials"
  name = "Tutorials+FAQs"
  link = "#tutorials"
  url = "/tutorials"
  weight = 2
  [menu.main.params]
  caption = "Einführung"
