baseURL = "https://brettimkopf.github.io/KackenAufWacken"
languageCode = "de-de"
title = "Kacken auf Wacken"
theme = "zen"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[params]
favicon = "favicon.png"
icon = "favicon.png"
sitename = false
copyright = "[© BrettImKopf](https://github.com/BrettImKopf/KackenAufWacken)"
poweredby = true
menuInHeader = false        # Move the main menu to the header, default false.
mobileMenuOutline = true   # Mobil menu button as outline, default false.
[[menu.main]]
  identifier = "main"
  name = "Startseite"
  link = "#main"
  url = "/"
  weight = 1
[[menu.main]]
  identifier = "zubehoer"
  name = "Zubehör"
  link = "#zubehoer"
  url = "/zubehoer"
  weight = 2
[[menu.main]]
  identifier = "quickstart"
  name = "Quickstart"
  link = "#quickstart"
  url = "/quickstart"
  weight = 3
[[menu.main]]
  identifier = "introduction"
  name = "Einführung"
  link = "#introduction"
  url = "/introduction"
  weight = 4

[[menu.main]]
  identifier = "tutorials"
  name = "Tutorials+FAQs"
  link = "#tutorials"
  url = "/tutorials"
  weight = 5