baseURL = "https://brettimkopf.github.io/Kacken-auf-Wacken"
languageCode = 'de_de'
title = 'Kacken auf Wacken'
theme = "hello-friend-ng"
defaultContentLanguage = "en"
EnableThemeToggle = "true"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[languages]
  [languages.en]
    languageName = "English"
    weight = 1

  [languages.de]
    languageName = "Deutsch"
    weight = 2

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"
	EnableThemeToggle = "true"
	
  # Subtitle for home
  homeSubtitle = "A simple and beautiful blog"

	
[params.logo]
	path = "images/logo.png"
    alt = "Kacjen auf Wacken"
 [[menu.main]]
  identifier = "story"
  name = "Story"
  link = "#story"
  url = "/story"
  weight = 1
[[menu.main]]
  identifier = "zubehoer"
  name = "Zubehör"
  link = "#zubehoer"
  url = "/zubehoer"
  weight = 2
[[menu.main]]
  identifier = "vorbereitung"
  name = "Vorbereitung"
  link = "#vorbereitung"
  url = "/vorbereitung"
  weight = 3
[[menu.main]]
  identifier = "quickstart"
  name = "Kurzanleitung"
  link = "#quickstart"
  url = "/quickstart"
  weight = 4
  [menu.main.params]
  caption = "Schnelleinstieg für Eilige"
[[menu.main]]
  identifier = "rules"
  name = "Spielregeln"
  link = "#rules"
  url = "/rules"
  weight = 5
  [menu.main.params]
  caption = "Die Regeln im Detail"
[[menu.main]]
  identifier = "faq"
  name = "FAQs"
  link = "#faq"
  url = "/faq"
  weight = 6
  [menu.main.params]
  caption = "Fragen und Antworten"
[[menu.main]]
  identifier = "main"
  name = "Startseite"
  link = "#main"
  url = "/"
  weight = 7
  [menu.main.params]
  caption = "Zurück zur Hauptseite"