baseURL = "https://brettimkopf.github.io/Kacken-auf-Wacken"
languageCode = "de-de"
title = "Kacken auf Wacken"
theme = "zen"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[params]
favicon = "favicon.png"
icon = "favicon.png"
sitename = false
copyright = "© [BrettImKopf](https://github.com/BrettImKopf/Kacken-auf-Wacken)"
poweredby = true
menuInHeader = false        # Move the main menu to the header, default false.
mobileMenuOutline = true   # Mobil menu button as outline, default false.

[[menu.main]]
  identifier = "story"
  name = "Story"
  link = "#story"
  url = "/story"
  weight = 1
  [menu.main.params]
  caption = "Worum geht's?"
[[menu.main]]
  identifier = "zubehoer"
  name = "Zubehör"
  link = "#zubehoer"
  url = "/zubehoer"
  weight = 2
  [menu.main.params]
  caption = "Welche Karten gibt es?"
[[menu.main]]
  identifier = "vorbereitung"
  name = "Vorbereitung"
  link = "#vorbereitung"
  url = "/vorbereitung"
  weight = 3
  [menu.main.params]
  caption = "Wie werden die Karten verteilt und ausgelegt?"
[[menu.main]]
  identifier = "quickstart"
  name = "Kurzanleitung"
  link = "#quickstart"
  url = "/quickstart"
  weight = 4
  [menu.main.params]
  caption = "Schnelleinstieg für Eilige"
[[menu.main]]
  identifier = "rules"
  name = "Spielregeln"
  link = "#rules"
  url = "/rules"
  weight = 5
  [menu.main.params]
  caption = "Die Regeln im Detail"
[[menu.main]]
  identifier = "faq"
  name = "FAQs"
  link = "#faq"
  url = "/faq"
  weight = 6
  [menu.main.params]
  caption = "Fragen und Antworten"
[[menu.main]]
  identifier = "main"
  name = "Startseite"
  link = "#main"
  url = "/"
  weight = 7
  [menu.main.params]
  caption = "Zurück zur Hauptseite"


