name: Deploy Hugo Site to GitHub Pages

on:
  push:
    branches:
      - main  # Ändere dies, falls dein Hauptbranch anders heißt (z. B. 'master')

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'  # oder eine spezifische Version angeben

    - name: Build the site
      run: hugo --minify

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public  # Stelle sicher, dass dies auf den richtigen Build-Pfad verweist
